language: java
script: mvn install -DskipTests=true -DrepoToken=hsPhY0vnF9N4LWtTyyQ2HLjJ3KFzrruRo
notifications:
  slack: legendcraft:HIsRxeJX20Z002YvPzziRvyM
after_success:
  - mvn clean org.eluder.coveralls:coveralls-maven-plugin:report
